# Generated by Django 3.1.5 on 2021-01-11 02:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(default=None, max_length=255, unique=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(
                    null=True, verbose_name='Text')),
                ('featured', models.ImageField(blank=True,
                                               upload_to='media_root/static/media/portfolio')),
                ('limitation', models.CharField(choices=[('Artificial Intelligence', (('ai', 'Artificial Intelligence'),)), ('Buy and Sell', ((
                    'cryptos', 'Cryptocurrencies'),)), ('Forex Education', (('forex', 'Forex '),))], max_length=50, null=True)),
                ('published_date', models.DateTimeField(auto_now_add=True,
                                                        verbose_name=datetime.datetime(2021, 1, 11, 2, 2, 41, 930006, tzinfo=utc))),
            ],
        ),
    ]
