# Generated by Django 3.0.11 on 2021-02-02 23:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_auto_20210203_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('Cryptocurrency', 'Cryptocurrency'), ('DL', 'Deep Learning'), ('ML', 'Machine Learning'), ('WD', 'Web Development')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='client',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=datetime.datetime(2021, 2, 2, 23, 47, 2, 784436, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='website',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
