# Generated by Django 3.0.11 on 2021-02-03 19:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_auto_20210203_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=datetime.datetime(2021, 2, 3, 19, 40, 6, 917278, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='website',
            field=models.URLField(blank=True, default='No Website', max_length=100, null=True),
        ),
    ]
