# Generated by Django 3.0.11 on 2021-02-15 10:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_auto_20210215_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=datetime.datetime(2021, 2, 15, 10, 6, 22, 418613, tzinfo=utc)),
        ),
    ]
