# Generated by Django 3.1.5 on 2021-01-06 12:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210106_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author_picture',
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='media_root/static/media/blog_pix'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 1, 6, 12, 40, 37, 440909, tzinfo=utc)),
        ),
    ]
