# Generated by Django 3.1.5 on 2021-01-06 13:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210106_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media_root/static/media/people'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 1, 6, 13, 0, 59, 969839, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='image',
            field=models.ImageField(null=True, upload_to='media_root/static/media/testimonials'),
        ),
    ]
