# Generated by Django 3.1.5 on 2021-01-06 13:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210106_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='types',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 1, 6, 13, 54, 16, 938144, tzinfo=utc)),
        ),
    ]
