# Generated by Django 3.1.5 on 2021-01-06 17:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0013_auto_20210106_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 1, 6, 17, 37, 2, 123101, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_field', models.SlugField(allow_unicode=True, max_length=60, unique=True)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(verbose_name=datetime.datetime(2021, 1, 6, 17, 37, 2, 123101, tzinfo=utc))),
                ('approved_comment', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentor_name', to=settings.AUTH_USER_MODEL)),
                ('blog_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blog')),
            ],
        ),
    ]
