# Generated by Django 3.1.5 on 2021-01-06 17:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210106_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 1, 6, 17, 47, 36, 504471, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 1, 6, 17, 47, 36, 508462, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='slug_field',
            field=models.SlugField(blank=True, max_length=60, unique=True),
        ),
    ]
