# Generated by Django 3.1.5 on 2021-01-15 08:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_auto_20210115_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 1, 15, 8, 2, 28, 831884, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to='blog.about'),
        ),
    ]
