# Generated by Django 3.1.5 on 2021-01-15 10:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0036_auto_20210115_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='about_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 1, 15, 10, 51, 18, 968613, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='comment_name', to='blog.about'),
        ),
    ]
