# Generated by Django 3.0.11 on 2021-01-20 15:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments', '0003_add_submit_date_index'),
        ('blog', '0039_auto_20210118_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 1, 20, 15, 42, 22, 527660, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='MyCustomComment',
        ),
    ]
