# Generated by Django 3.0.11 on 2021-02-02 23:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_auto_20210203_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 2, 2, 23, 47, 2, 775689, tzinfo=utc)),
        ),
    ]
