# Generated by Django 3.0.11 on 2021-02-03 19:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_auto_20210203_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 2, 3, 19, 40, 6, 910295, tzinfo=utc)),
        ),
    ]
