# Generated by Django 3.0.11 on 2021-02-03 20:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_auto_20210203_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 2, 3, 20, 34, 26, 853840, tzinfo=utc)),
        ),
    ]
