# Generated by Django 3.0.11 on 2021-02-04 10:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0044_auto_20210203_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 2, 4, 10, 42, 26, 595317, tzinfo=utc)),
        ),
    ]
