# Generated by Django 3.0.11 on 2021-02-04 13:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0045_auto_20210204_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 2, 4, 13, 6, 4, 866500, tzinfo=utc)),
        ),
    ]
