# Generated by Django 3.0.11 on 2021-02-14 15:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0046_auto_20210204_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 2, 14, 15, 45, 41, 654214, tzinfo=utc)),
        ),
    ]
