# Generated by Django 3.0.11 on 2021-02-15 09:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0047_auto_20210214_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 2, 15, 9, 57, 49, 290129, tzinfo=utc)),
        ),
    ]
