# Generated by Django 3.0.11 on 2021-02-15 10:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0049_auto_20210215_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 2, 15, 10, 9, 38, 490335, tzinfo=utc)),
        ),
    ]
