# Generated by Django 3.0.11 on 2021-02-18 18:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0051_auto_20210215_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 2, 18, 18, 49, 51, 954528, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tag',
            name='types',
            field=models.CharField(choices=[('Artificial Intelligence', (('Machine Learning', 'ML'), ('Deep Learning', 'DL'), ('Computer Vision', 'CV'))), ('Deployment', (('Django', 'DJ'), ('Streamlit', 'ST'))), ('Buy and Sell', (('BTC', 'buy btc'), ('Ethereum(ETH)', 'buy ethereum'), ('Ripple(XRP)', 'buy ripple'), ('EOS(EOS)', 'buy eos'), ('DASH(DASH)', 'buy dash'), ('Binance Coin(BNB)', 'buy binance coin'), ('Monero(XMR)', 'buy monero'), ('Steem(STEEM)', 'buy steem'), ('Cardano(ADA)', 'buy cardano'), ('Neo(NEO)', 'buy neo'), ('Litecoin(LTC)', 'buy litecoin'), ('Tron(TRX)', 'buy tron'))), ('Digital Wallet', (('Hardware wallet', 'hardware wallet'), ('Bitcoin wallet', 'BTC'), ('Ethereum Wallet', 'ethereum wallet'))), ('Crypto Exchange', (('Name of exchange', 'name of exchange'),)), ('Mining Guide', (('BTC mining', 'btc mining'),)), ('Forex Education', (('How to trade Forex', 'how to trade forex'),)), ('Forex Trading', (('Technical Analysis', 'technical'), ('Psychological Analysis', 'Psychology'), ('Trading System', 'trading system'))), ('Passive Income', 'Passive Income')], max_length=50),
        ),
    ]
